import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { motion } from "framer-motion";
import { FileText, AlertTriangle, Scale } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground font-sans selection:bg-primary/30">
      <Navbar />
      <main className="pt-32 pb-20 container mx-auto px-6 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="prose prose-invert prose-lg max-w-none"
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 rounded-xl bg-primary/10 border border-primary/20">
              <FileText className="w-8 h-8 text-primary" />
            </div>
            <h1 className="text-4xl font-heading font-bold m-0">Terms of Service</h1>
          </div>
          
          <p className="lead text-xl text-muted-foreground">
            Last Updated: December 06, 2025
          </p>

          <div className="glass-panel p-8 rounded-2xl border border-white/5 my-12">
            <h3 className="text-primary mt-0">1. System Access</h3>
            <p>
              Access to TriFused infrastructure is a privilege, not a right. We reserve the right to terminate connections from any node detected attempting unauthorized penetration testing or DDoS vectors.
            </p>

            <h3 className="text-primary">2. Liability Limitation</h3>
            <p>
              While our AI models operate with 99.9% accuracy, TriFused is not liable for hallucinations, predictive errors, or sentient uprisings resulting from the misuse of our generative engines.
            </p>

            <h3 className="text-primary">3. Intellectual Property</h3>
            <p>
              All code, neural weights, and visual assets generated by the TriFused platform remain the intellectual property of TriFused Technologies unless explicitly transferred via a smart contract.
            </p>
          </div>
        </motion.div>
      </main>
      <Footer />
    </div>
  );
}
